## Setup

In [1]:
import json
import re
import datetime
from collections import OrderedDict

import pandas as pd
import pandas.io.json as pj
from IPython.core.debugger import set_trace

import tbap.api as api
import tbap.server as server

In [2]:
key = "6Sx6a2gOyNWwNNTAd9UYBOpWp7MxaNrZgO4CqConwJwwDooKQV3DbZXvnk8TBL7A"
username = "stacy.k.irwin@gmail.com"
sn = api.Session(username, key)
snj = api.Session(username, key, data_format="json")

# Display floating point numbers in fixed format within dataframes.
pd.options.display.float_format = '{:f}'.format

# Examples

### get_events()

In [3]:
events = api.get_events(sn, year=2016)

In [4]:
events.query("city=='Auburn'")

,address,city,country,division_keys,end_date,event_code,event_type,event_type_string,first_event_code,first_event_id,...,state_prov,timezone,webcasts,website,week,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,,,,,,,,,
2016waahs,"711 E Main St, Auburn, WA 98002, USA",Auburn,USA,[],2016-04-03,waahs,1,District,WAAHS,17473.000000,...,WA,America/Los_Angeles,"[{'channel': '17281416', 'type': 'ustream'}]",http://www.firstwa.org,5.000000,2016,pnw,Pacific Northwest,2016pnw,2016.000000
2016waamv,"28900 124th Ave SE, Auburn, WA 98092, USA",Auburn,USA,[],2016-03-05,waamv,1,District,WAAMV,17463.000000,...,WA,America/Los_Angeles,"[{'channel': '17281416', 'type': 'ustream'}]",http://www.firstwa.org/,1.000000,2016,pnw,Pacific Northwest,2016pnw,2016.000000

In [5]:
events.shape

(203, 32)

In [6]:
events = api.get_events(sn, year=2016, response="simple")

In [7]:
events.tail()

,city,country,end_date,event_code,event_type,name,start_date,state_prov,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,
2016week0,Merrimack,USA,2016-02-20,week0,100,Week 0,2016-02-20,NH,2016,None,None,None,nan
2016wimi,Milwaukee,USA,2016-03-26,wimi,0,Wisconsin Regional,2016-03-23,WI,2016,None,None,None,nan
2016wiwi,Wolcott,USA,2016-06-11,wiwi,99,Where is Wolcott Invitational,2016-06-11,CT,2016,None,None,None,nan
2016wmri,Zeeland,USA,2016-10-29,wmri,99,West Michigan Robotics Invitational,2016-10-29,MI,2016,None,None,None,nan
2016wvrox,Morgantown,USA,2016-08-06,wvrox,99,West Virginia RObotics eXtreme,2016-08-05,WV,2016,None,None,None,nan

In [8]:
events.shape

(203, 13)

In [9]:
events = api.get_events(sn, year=2016, response="keys")

In [10]:
events.head()

        key
0  2016abca
1  2016alhu
2   2016arc
3  2016arlr
4  2016aroz

In [11]:
events.shape

(203, 1)

In [12]:
events = api.get_events(sn, district="2017pnw")

In [13]:
events.tail()

,address,city,country,district.abbreviation,district.display_name,district.key,district.year,division_keys,end_date,event_code,...,playoff_type_string,postal_code,short_name,start_date,state_prov,timezone,webcasts,website,week,year
key,,,,,,,,,,,,,,,,,,,,,
2017waamv,"28900 124th Ave SE, Auburn, WA 98092, USA",Auburn,USA,pnw,Pacific Northwest,2017pnw,2017,[],2017-03-05,waamv,...,None,98092,Auburn Mountainview,2017-03-03,WA,America/Los_Angeles,"[{'channel': '17281416', 'type': 'ustream'}, {...",http://www.firstwa.org/,0,2017
2017waell,"400 E University Way, Ellensburg, WA 98926, USA",Ellensburg,USA,pnw,Pacific Northwest,2017pnw,2017,[],2017-03-18,waell,...,None,98926,Central Washington University,2017-03-16,WA,America/Los_Angeles,"[{'channel': 'firstwa_red', 'type': 'twitch'}]",http://www.firstwa.org,2,2017
2017wamou,"314 N 9th St, Mt Vernon, WA 98273, USA",Mount Vernon,USA,pnw,Pacific Northwest,2017pnw,2017,[],2017-03-19,wamou,...,None,98273,Mount Vernon,2017-03-17,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue', 'type': 'twitch'}]",http://www.firstwa.org/,2,2017
2017wasno,"7401 144th Pl SE, Snohomish, WA 98296, USA",Snohomish,USA,pnw,Pacific Northwest,2017pnw,2017,[],2017-03-26,wasno,...,None,98296,Glacier Peak,2017-03-24,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue', 'type': 'twitch'}]",http://www.firstwa.org/,3,2017
2017waspo,"8301 E Buckeye Ave, Spokane, WA 99212, USA",Spokane,USA,pnw,Pacific Northwest,2017pnw,2017,[],2017-03-04,waspo,...,None,99212,West Valley,2017-03-02,WA,America/Los_Angeles,"[{'channel': 'firstwa_red', 'type': 'twitch'}]",http://www.firstwa.org,0,2017

In [14]:
events.shape

(10, 32)

In [15]:
events = api.get_events(sn, district="2017pnw", response="simple")

In [16]:
events.head()

,city,country,district.abbreviation,district.display_name,district.key,district.year,end_date,event_code,event_type,name,start_date,state_prov,year
key,,,,,,,,,,,,,
2017orlak,Lake Oswego,USA,pnw,Pacific Northwest,2017pnw,2017,2017-04-01,orlak,1,PNW District - Lake Oswego Event,2017-03-30,OR,2017
2017orore,Clackamas,USA,pnw,Pacific Northwest,2017pnw,2017,2017-03-25,orore,1,PNW District - Clackamas Academy of Industrial...,2017-03-23,OR,2017
2017orwil,Wilsonville,USA,pnw,Pacific Northwest,2017pnw,2017,2017-03-11,orwil,1,PNW District - Wilsonville Event,2017-03-09,OR,2017
2017pncmp,Cheney,USA,pnw,Pacific Northwest,2017pnw,2017,2017-04-08,pncmp,2,Pacific Northwest District Championship,2017-04-05,WA,2017
2017waahs,Auburn,USA,pnw,Pacific Northwest,2017pnw,2017,2017-04-02,waahs,1,PNW District - Auburn Event,2017-03-31,WA,2017

In [17]:
events.shape

(10, 13)

In [18]:
events = api.get_events(sn, district="2017pnw", response="keys")

In [19]:
events.head()

         key
0  2017orlak
1  2017orore
2  2017orwil
3  2017pncmp
4  2017waahs

In [20]:
events = api.get_events(sn, team="frc1318", year=2017)

In [21]:
events.head()

,address,city,country,division_keys,end_date,event_code,event_type,event_type_string,first_event_code,first_event_id,...,state_prov,timezone,webcasts,website,week,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,,,,,,,,,
2017cmptx,"1001 Avenida De Las Americas, Houston, TX 7701...",Houston,USA,"[2017carv, 2017gal, 2017hop, 2017new, 2017roe,...",2017-04-22,cmptx,4,Championship Finals,CMPTX,nan,...,TX,America/Chicago,"[{'channel': 'firstinspires', 'type': 'twitch'}]",http://None,nan,2017,None,None,None,nan
2017pncmp,"526 5th St, Cheney, WA 99004, USA",Cheney,USA,[],2017-04-08,pncmp,2,District Championship,PNCMP,22651.000000,...,WA,America/Los_Angeles,"[{'channel': 'firstwa_red', 'type': 'twitch'},...",http://www.firstwa.org,5.000000,2017,pnw,Pacific Northwest,2017pnw,2017.000000
2017tur,"1001 Avenida De Las Americas, Houston, TX 7701...",Houston,USA,[],2017-04-22,tur,3,Championship Division,TUR,nan,...,TX,America/Chicago,"[{'channel': 'FIRSTInspires_Turing', 'type': '...",None,nan,2017,None,None,None,nan
2017waahs,"711 E Main St, Auburn, WA 98002, USA",Auburn,USA,[],2017-04-02,waahs,1,District,WAAHS,22639.000000,...,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue', 'type': 'twitch'}]",http://www.firstwa.org,4.000000,2017,pnw,Pacific Northwest,2017pnw,2017.000000
2017waamv,"28900 124th Ave SE, Auburn, WA 98092, USA",Auburn,USA,[],2017-03-05,waamv,1,District,WAAMV,22629.000000,...,WA,America/Los_Angeles,"[{'channel': '17281416', 'type': 'ustream'}, {...",http://www.firstwa.org/,0.000000,2017,pnw,Pacific Northwest,2017pnw,2017.000000

In [22]:
events.shape

(8, 32)

In [23]:
events = api.get_events(sn, team="frc1318", year=2016, response="simple")

In [24]:
events.head()

,city,country,end_date,event_code,event_type,name,start_date,state_prov,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,
2016arc,St. Louis,USA,2016-04-30,arc,3,Archimedes Division,2016-04-27,MO,2016,None,None,None,nan
2016orphi,Philomath,USA,2016-03-26,orphi,1,PNW District - Philomath Event,2016-03-24,OR,2016,pnw,Pacific Northwest,2016pnw,2016.000000
2016pncmp,Portland,USA,2016-04-09,pncmp,2,Pacific Northwest District Championship sponso...,2016-04-06,OR,2016,pnw,Pacific Northwest,2016pnw,2016.000000
2016waamv,Auburn,USA,2016-03-05,waamv,1,PNW District - Auburn Mountainview Event,2016-03-03,WA,2016,pnw,Pacific Northwest,2016pnw,2016.000000
2016waell,Ellensburg,USA,2016-03-19,waell,1,PNW District - Central Washington University E...,2016-03-17,WA,2016,pnw,Pacific Northwest,2016pnw,2016.000000

In [25]:
events = api.get_events(sn, team="frc1318", year=2016, response="keys")

In [26]:
events.head()

         key
0    2016arc
1  2016orphi
2  2016pncmp
3  2016waamv
4  2016waell

In [34]:
event = api.get_events(sn, event="2017tur")

In [35]:
event

,address,city,country,district,division_keys,end_date,event_code,event_type,event_type_string,first_event_code,...,playoff_type_string,postal_code,short_name,start_date,state_prov,timezone,webcasts,website,week,year
key,,,,,,,,,,,,,,,,,,,,,
2017tur,"1001 Avenida De Las Americas, Houston, TX 7701...",Houston,USA,nan,[],2017-04-22,tur,3,Championship Division,TUR,...,Elimination Bracket (8 Alliances),77010,Turing,2017-04-19,TX,America/Chicago,"[{'channel': 'FIRSTInspires_Turing', 'type': '...",nan,nan,2017

In [36]:
event.shape

(1, 29)

In [40]:
event = api.get_events(sn, event="2017tur", response="simple")

In [41]:
event

,city,country,district,end_date,event_code,event_type,name,start_date,state_prov,year
key,,,,,,,,,,
2017tur,Houston,USA,nan,2017-04-22,tur,3,Turing Division,2017-04-19,TX,2017

In [42]:
event.shape

(1, 10)

### get_rankings()

In [43]:
rankings = api.get_rankings(sn, "2017pnw")

AttributeError: module 'tbap.api' has no attribute 'get_rankings'

In [ ]:
rankings.query("team_key == 'frc1318'")