## Setup

In [2]:
import json
import re
import datetime
from collections import OrderedDict

import pandas as pd
import pandas.io.json as pj
from IPython.core.debugger import set_trace

import tbap.api as api
import tbap.server as server

import auth

In [3]:
key = auth.key
username = auth.username
sn = api.Session(username, key)
snj = api.Session(username, key, data_format="json")

# Display floating point numbers in fixed format within dataframes.
pd.options.display.float_format = '{:f}'.format

# Examples

### get_events()

In [4]:
events = api.get_events(sn, year=2019)

In [5]:
events.query("city=='Auburn'")

,address,city,country,division_keys,end_date,event_code,event_type,event_type_string,first_event_code,first_event_id,...,state_prov,timezone,webcasts,website,week,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,,,,,,,,,
2019waahs,"711 E Main St, Auburn, WA 98002, USA",Auburn,USA,[],2019-03-31,waahs,1,District,WAAHS,37488.000000,...,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue1', 'type': 'twitch'...",http://www.firstwa.org,4.000000,2019,pnw,Pacific Northwest,2019pnw,2019.000000
2019waamv,"28900 124th Ave SE, Auburn, WA 98092, USA",Auburn,USA,[],2019-03-10,waamv,1,District,WAAMV,37478.000000,...,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org/,1.000000,2019,pnw,Pacific Northwest,2019pnw,2019.000000

In [6]:
events.shape

(244, 32)

In [8]:
events = api.get_events(sn, year=2019, response="simple")

In [9]:
events.tail()

,city,country,end_date,event_code,event_type,name,start_date,state_prov,year,district_abbreviation,district_display_name,district_key,district_year
key,,,,,,,,,,,,,
2019wimi,Milwaukee,USA,2019-03-30,wimi,0,Wisconsin Regional,2019-03-27,WI,2019,None,None,None,nan
2019wiwi,Wolcott,USA,2019-06-01,wiwi,99,Where is Wolcott Invitational,2019-06-01,CT,2019,None,None,None,nan
2019wiws,West Salem,USA,2019-02-17,wiws,100,Seven Rivers Robotics Coalition Week Zero,2019-02-16,WI,2019,None,None,None,nan
2019wowcmp,Austintown,USA,2019-05-18,wowcmp,99,WOW Alliance Championship,2019-05-17,OH,2019,None,None,None,nan
2019zhrcc,Hangzhou Shi,China,2019-08-04,zhrcc,99,RCC Qianjiang International Robotics Invitatio...,2019-08-01,Zhejiang Sheng,2019,None,None,None,nan

In [10]:
events.shape

(244, 13)

In [11]:
events = api.get_events(sn, year=2019, response="keys")

In [12]:
events.head()

        key
0  2019abca
1  2019alhu
2   2019arc
3  2019arli
4  2019aroz

In [11]:
events.shape

(203, 1)

In [13]:
events = api.get_events(sn, district="2019pnw")

In [14]:
events.tail()

,address,city,country,district.abbreviation,district.display_name,district.key,district.year,division_keys,end_date,event_code,...,playoff_type_string,postal_code,short_name,start_date,state_prov,timezone,webcasts,website,week,year
key,,,,,,,,,,,,,,,,,,,,,
2019waamv,"28900 124th Ave SE, Auburn, WA 98092, USA",Auburn,USA,pnw,Pacific Northwest,2019pnw,2019,[],2019-03-10,waamv,...,Elimination Bracket (8 Alliances),98092,Auburn Mountainview,2019-03-08,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org/,1,2019
2019wamou,"314 N 9th St, Mt Vernon, WA 98273, USA",Mount Vernon,USA,pnw,Pacific Northwest,2019pnw,2019,[],2019-03-03,wamou,...,None,98273,Mount Vernon,2019-03-01,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org/,0,2019
2019wasno,"7401 144th Pl SE, Snohomish, WA 98296, USA",Snohomish,USA,pnw,Pacific Northwest,2019pnw,2019,[],2019-03-24,wasno,...,None,98296,Glacier Peak,2019-03-22,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue1', 'type': 'twitch'...",http://www.firstwa.org/,3,2019
2019waspo,"8301 E Buckeye Ave, Spokane, WA 99212, USA",Spokane,USA,pnw,Pacific Northwest,2019pnw,2019,[],2019-03-23,waspo,...,None,99212,West Valley,2019-03-21,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org,3,2019
2019wayak,"1301 S Fair Ave, Yakima, WA 98901, USA",Yakima,USA,pnw,Pacific Northwest,2019pnw,2019,[],2019-03-16,wayak,...,None,98901,SunDome,2019-03-14,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue1', 'type': 'twitch'...",http://www.firstwa.org/,2,2019

In [14]:
events.shape

(10, 32)

In [15]:
events = api.get_events(sn, district="2019pnw", response="simple")

In [16]:
events.head()

,city,country,district.abbreviation,district.display_name,district.key,district.year,end_date,event_code,event_type,name,start_date,state_prov,year
key,,,,,,,,,,,,,
2019orlak,Lake Oswego,USA,pnw,Pacific Northwest,2019pnw,2019,2019-03-30,orlak,1,PNW District Lake Oswego Event,2019-03-28,OR,2019
2019orore,Oregon City,USA,pnw,Pacific Northwest,2019pnw,2019,2019-03-16,orore,1,PNW District Clackamas Academy Event,2019-03-14,OR,2019
2019orwil,Wilsonville,USA,pnw,Pacific Northwest,2019pnw,2019,2019-03-09,orwil,1,PNW District Wilsonville Event,2019-03-07,OR,2019
2019pncmp,Tacoma,USA,pnw,Pacific Northwest,2019pnw,2019,2019-04-06,pncmp,2,Pacific Northwest FIRST District Championship,2019-04-03,WA,2019
2019waahs,Auburn,USA,pnw,Pacific Northwest,2019pnw,2019,2019-03-31,waahs,1,PNW District Auburn Event,2019-03-29,WA,2019

In [17]:
events.shape

(10, 13)

In [17]:
events = api.get_events(sn, district="2019pnw", response="keys")

In [18]:
events.head()

         key
0  2019orlak
1  2019orore
2  2019orwil
3  2019pncmp
4  2019waahs

In [19]:
events = api.get_events(sn, team="frc1318", year=2019)

In [20]:
events.head()

,address,city,country,district.abbreviation,district.display_name,district.key,district.year,division_keys,end_date,event_code,...,playoff_type_string,postal_code,short_name,start_date,state_prov,timezone,webcasts,website,week,year
key,,,,,,,,,,,,,,,,,,,,,
2019pncmp,"1500 Commerce St, Tacoma, WA 98402, USA",Tacoma,USA,pnw,Pacific Northwest,2019pnw,2019.000000,[],2019-04-06,pncmp,...,None,98402,Pacific Northwest FIRST,2019-04-03,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org,5.000000,2019
2019roe,"1001 Avenida De Las Americas, Houston, TX 7701...",Houston,USA,NaN,NaN,NaN,nan,[],2019-04-20,roe,...,None,77010,Roebling,2019-04-17,TX,America/Chicago,"[{'channel': 'firstinspires_roebling', 'type':...",None,nan,2019
2019waahs,"711 E Main St, Auburn, WA 98002, USA",Auburn,USA,pnw,Pacific Northwest,2019pnw,2019.000000,[],2019-03-31,waahs,...,None,98002,Auburn,2019-03-29,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue1', 'type': 'twitch'...",http://www.firstwa.org,4.000000,2019
2019wamou,"314 N 9th St, Mt Vernon, WA 98273, USA",Mount Vernon,USA,pnw,Pacific Northwest,2019pnw,2019.000000,[],2019-03-03,wamou,...,None,98273,Mount Vernon,2019-03-01,WA,America/Los_Angeles,"[{'channel': 'firstwa_red1', 'type': 'twitch'}...",http://www.firstwa.org/,0.000000,2019
2019wayak,"1301 S Fair Ave, Yakima, WA 98901, USA",Yakima,USA,pnw,Pacific Northwest,2019pnw,2019.000000,[],2019-03-16,wayak,...,None,98901,SunDome,2019-03-14,WA,America/Los_Angeles,"[{'channel': 'firstwa_blue1', 'type': 'twitch'...",http://www.firstwa.org/,2.000000,2019

In [22]:
events.shape

(8, 32)

In [21]:
events = api.get_events(sn, team="frc1318", year=2019, response="simple")

In [22]:
events.head()

,city,country,district.abbreviation,district.display_name,district.key,district.year,end_date,event_code,event_type,name,start_date,state_prov,year
key,,,,,,,,,,,,,
2019pncmp,Tacoma,USA,pnw,Pacific Northwest,2019pnw,2019.000000,2019-04-06,pncmp,2,Pacific Northwest FIRST District Championship,2019-04-03,WA,2019
2019roe,Houston,USA,NaN,NaN,NaN,nan,2019-04-20,roe,3,Roebling Division,2019-04-17,TX,2019
2019waahs,Auburn,USA,pnw,Pacific Northwest,2019pnw,2019.000000,2019-03-31,waahs,1,PNW District Auburn Event,2019-03-29,WA,2019
2019wamou,Mount Vernon,USA,pnw,Pacific Northwest,2019pnw,2019.000000,2019-03-03,wamou,1,PNW District Mount Vernon Event,2019-03-01,WA,2019
2019wayak,Yakima,USA,pnw,Pacific Northwest,2019pnw,2019.000000,2019-03-16,wayak,1,PNW District SunDome Event,2019-03-14,WA,2019

In [23]:
events = api.get_events(sn, team="frc1318", year=2019, response="keys")

In [24]:
events.head()

         key
0  2019pncmp
1    2019roe
2  2019waahs
3  2019wamou
4  2019wayak

In [25]:
event = api.get_events(sn, event="2019tur")

In [26]:
event

,address,city,country,district,division_keys,end_date,event_code,event_type,event_type_string,first_event_code,...,playoff_type_string,postal_code,short_name,start_date,state_prov,timezone,webcasts,website,week,year
key,,,,,,,,,,,,,,,,,,,,,
2019tur,"1001 Avenida De Las Americas, Houston, TX 7701...",Houston,USA,nan,[],2019-04-20,tur,3,Championship Division,TUR,...,nan,77010,Turing,2019-04-17,TX,America/Chicago,"[{'channel': 'firstinspires_turing', 'type': '...",nan,nan,2019

In [27]:
event.shape

(1, 29)

In [28]:
event = api.get_events(sn, event="2019tur", response="simple")

In [29]:
event

,city,country,district,end_date,event_code,event_type,name,start_date,state_prov,year
key,,,,,,,,,,
2019tur,Houston,USA,nan,2019-04-20,tur,3,Turing Division,2019-04-17,TX,2019

In [30]:
event.shape

(1, 10)

### get_rankings()

In [31]:
rankings = api.get_event_rankings(sn, "2019pncmp")

In [32]:
rankings.head()

,team,matches_played,Total Ranking Points,Ranking Score,Cargo,Hatch Panel,HAB Climb,Sandstorm Bonus,wins,losses,ties,dq,qual_average
rank,,,,,,,,,,,,,
1,frc2046,12,36,3.000000,342.000000,208.000000,192.000000,174.000000,11,1,0,0,None
2,frc4911,12,35,2.910000,384.000000,226.000000,201.000000,156.000000,10,2,0,0,None
3,frc4488,12,35,2.910000,300.000000,178.000000,228.000000,177.000000,10,2,0,0,None
4,frc2910,12,33,2.750000,390.000000,282.000000,192.000000,171.000000,11,1,0,0,None
5,frc2990,12,33,2.750000,390.000000,190.000000,219.000000,147.000000,10,2,0,0,None

In [33]:
rankings.shape

(64, 13)